version: "3.8"

services:
  telegraph_bot_db:
    container_name: "ilia_telegraph_bot_db"
    restart: always
    image: postgres:12.20-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./new_database.sql:/docker-entrypoint-initdb.d/new_database.sql
    ports:
      - ${DB_EXT_PORT}:5432

  telegraph_bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    image: ilia-telegraph-bot:latest
    container_name: "ilia_telegraph_bot"
    restart: always

volumes:
  pg_data:
    external: true
